import { create } from 'zustand';
import { clearState, loadState, saveState } from '../services/storageService';
import { CRAFTING_RECIPES, XP_REWARDS } from '../constants/balance';
import { Camp, Equipment, EquipmentItem, Inventory, Resource, ResourceType, Tribe, User } from '../types/game';
import { emptyInventory, levelUpCampIfReady } from '../utils/camp';
import { levelFromXp } from '../utils/xp';
type State={hydrated:boolean; user?:User; inventory:Inventory; equipment:Equipment; camp?:Camp; resources:Resource[]; greetedPlayerIds:string[]; stats:{totalXp:number;level:number;resourcesCollected:number;itemsCrafted:number;resourcesContributed:number;playersGreeted:number;campContributionScore:number}; hydrate:()=>Promise<void>; createProfile:(u:string,t:Tribe)=>void; addXp:(n:number)=>void; setResources:(r:Resource[])=>void; collectResource:(id:string)=>void; craft:(item:EquipmentItem)=>boolean; contribute:(amounts:Inventory)=>boolean; greet:(id:string)=>boolean; reset:()=>Promise<void>};
const initial={hydrated:false, inventory:emptyInventory(), equipment:{spear:0,axe:0,torch:0}, resources:[], greetedPlayerIds:[], stats:{totalXp:0,level:1,resourcesCollected:0,itemsCrafted:0,resourcesContributed:0,playersGreeted:0,campContributionScore:0}};
const persist=(s:State)=>saveState({user:s.user,inventory:s.inventory,equipment:s.equipment,camp:s.camp,resources:s.resources,greetedPlayerIds:s.greetedPlayerIds,stats:s.stats}).catch(()=>{});
export const useGameStore=create<State>((set,get)=>({...initial,
 hydrate:async()=>{ const saved=await loadState<Partial<State>>(); set({...initial,...saved,hydrated:true}); },
 createProfile:(username,tribe)=>set(s=>{ const user={id:`user-${Date.now()}`,username,tribe,xp:0,level:1}; const camp={tribe,level:0 as const,progress:emptyInventory()}; const ns={...s,user,camp}; persist(ns as State); return ns; }),
 addXp:(n)=>set(s=>{ if(!s.user)return s; const xp=s.user.xp+n; const level=levelFromXp(xp); const ns={...s,user:{...s.user,xp,level},stats:{...s.stats,totalXp:xp,level}}; persist(ns as State); return ns; }),
 setResources:(resources)=>set(s=>{const ns={...s,resources}; persist(ns as State); return ns;}),
 collectResource:(id)=>{ const r=get().resources.find(x=>x.id===id && !x.collected); if(!r)return; set(s=>{ const inv={...s.inventory,[r.type]:s.inventory[r.type]+1}; const xp=(s.user?.xp??0)+XP_REWARDS.collectResource; const ns={...s,inventory:inv,resources:s.resources.map(x=>x.id===id?{...x,collected:true}:x),user:s.user&&{...s.user,xp,level:levelFromXp(xp)},stats:{...s.stats,totalXp:xp,level:levelFromXp(xp),resourcesCollected:s.stats.resourcesCollected+1}}; persist(ns as State); return ns; }); },
 craft:(item)=>{ const recipe=CRAFTING_RECIPES[item]; const inv=get().inventory; const ok=Object.entries(recipe).every(([k,v])=>inv[k as ResourceType]>=Number(v)); if(!ok)return false; set(s=>{ const next={...s.inventory}; Object.entries(recipe).forEach(([k,v])=>next[k as ResourceType]-=Number(v)); const xp=(s.user?.xp??0)+XP_REWARDS.craftItem; const ns={...s,inventory:next,equipment:{...s.equipment,[item]:s.equipment[item]+1},user:s.user&&{...s.user,xp,level:levelFromXp(xp)},stats:{...s.stats,totalXp:xp,level:levelFromXp(xp),itemsCrafted:s.stats.itemsCrafted+1}}; persist(ns as State); return ns; }); return true; },
 contribute:(amounts)=>{ const inv=get().inventory; const total=amounts.wood+amounts.stone+amounts.food; if(!get().camp || total<=0 || amounts.wood>inv.wood || amounts.stone>inv.stone || amounts.food>inv.food)return false; set(s=>{ const xp=(s.user?.xp??0)+total; const camp=levelUpCampIfReady({...s.camp!,progress:{wood:s.camp!.progress.wood+amounts.wood,stone:s.camp!.progress.stone+amounts.stone,food:s.camp!.progress.food+amounts.food}}); const ns={...s,inventory:{wood:s.inventory.wood-amounts.wood,stone:s.inventory.stone-amounts.stone,food:s.inventory.food-amounts.food},camp,user:s.user&&{...s.user,xp,level:levelFromXp(xp)},stats:{...s.stats,totalXp:xp,level:levelFromXp(xp),resourcesContributed:s.stats.resourcesContributed+total,campContributionScore:s.stats.campContributionScore+total}}; persist(ns as State); return ns; }); return true; },
 greet:(id)=>{ if(get().greetedPlayerIds.includes(id))return false; set(s=>{ const xp=(s.user?.xp??0)+XP_REWARDS.greetPlayer; const ns={...s,greetedPlayerIds:[...s.greetedPlayerIds,id],user:s.user&&{...s.user,xp,level:levelFromXp(xp)},stats:{...s.stats,totalXp:xp,level:levelFromXp(xp),playersGreeted:s.stats.playersGreeted+1}}; persist(ns as State); return ns;}); return true; },
 reset:async()=>{ await clearState(); set({...initial,hydrated:true}); }
}));
