import { useState } from 'react';
import { TextInput, View } from 'react-native';
import { Body, Button, HUDCard, PanelSection, ResourceBar, Screen, ScreenHeader } from '../components/ui';
import { BASE_LEVEL_NAMES, CAMP_LEVEL_REQUIREMENTS } from '../constants/balance';
import { useGameStore } from '../store/gameStore';
import { Inventory, ResourceType } from '../types/game';
import { campProgressPercent } from '../utils/camp';
import { colors, space } from '../theme/theme';
export function CampScreen() { const camp = useGameStore(s => s.camp); const inv = useGameStore(s => s.inventory); const contribute = useGameStore(s => s.contribute); const [amounts, setAmounts] = useState<Inventory>({ data: 0, energy: 0, materials: 0 }); if (!camp) return null; const req = CAMP_LEVEL_REQUIREMENTS[camp.level]; return <Screen><ScreenHeader title="Base Network" kicker="Infrastructure uplink"/><HUDCard><Body>BASE {BASE_LEVEL_NAMES[camp.level] ?? 'REGIONAL COMMAND'} // LEVEL {camp.level + 1}</Body></HUDCard><PanelSection title="Resource Progress">{req ? (['data', 'energy', 'materials'] as ResourceType[]).map(t => <HUDCard key={t}><ResourceBar label={t} value={camp.progress[t]} max={req[t]} accent={t === 'energy' ? colors.blue : t === 'materials' ? colors.amber : colors.cyan}/><Body>{Math.round(campProgressPercent(camp, t) * 100)}% SYNCHRONIZED</Body></HUDCard>) : <HUDCard><Body>FORTRESS CAPACITY ONLINE. REGIONAL COMMAND FUNCTIONS STANDBY.</Body></HUDCard>}</PanelSection><PanelSection title="Contribution Panel"><HUDCard>{(['data', 'energy', 'materials'] as ResourceType[]).map(t => <View key={t} style={{ gap: space.xs }}><Body>{t.toUpperCase()} // OWNED {inv[t]}</Body><TextInput value={amounts[t] ? String(amounts[t]) : ''} keyboardType="number-pad" placeholder="000" placeholderTextColor={colors.muted} onChangeText={v => setAmounts(a => ({ ...a, [t]: Math.min(inv[t], Math.max(0, Number(v) || 0)) }))} style={{ borderWidth: 1, borderColor: colors.line, color: colors.text, padding: space.sm, letterSpacing: 2 }}/></View>)}<Button onPress={() => { contribute(amounts); setAmounts({ data: 0, energy: 0, materials: 0 }); }}>Upload to Base</Button></HUDCard></PanelSection></Screen>; }
