import { useState } from 'react';
import { TextInput, View } from 'react-native';
import { ActionFeedback, Body, Button, EmptyState, HUDCard, PanelSection, ResourceBar, Screen, ScreenHeader } from '../components/ui';
import { BASE_LEVEL_NAMES, CAMP_LEVEL_REQUIREMENTS } from '../constants/balance';
import { useGameStore } from '../store/gameStore';
import { Inventory, ResourceType } from '../types/game';
import { campProgressPercent } from '../utils/camp';
import { colors, space, tribeMeta } from '../theme/theme';
const types: ResourceType[] = ['data','energy','materials'];
export function CampScreen() { const camp = useGameStore(s => s.camp); const inv = useGameStore(s => s.inventory); const contribute = useGameStore(s => s.contribute); const [amounts, setAmounts] = useState<Inventory>({ data: 0, energy: 0, materials: 0 }); const [feedback,setFeedback]=useState(''); if (!camp) return <Screen><EmptyState title="No Base" body="Initialize an agent profile to deploy your first command base."/></Screen>; const req = CAMP_LEVEL_REQUIREMENTS[camp.level]; const total=amounts.data+amounts.energy+amounts.materials; const valid=total>0 && types.every(t=>amounts[t]>=0 && amounts[t]<=inv[t]); return <Screen><ScreenHeader title="Base Network" kicker="Infrastructure uplink"/><HUDCard><Body>{BASE_LEVEL_NAMES[camp.level] ?? 'REGIONAL COMMAND'} // LEVEL {camp.level + 1}</Body><Body>OWNER // {tribeMeta[camp.tribe].label} CLAN GRID</Body><Body>AP REWARD PREVIEW // {total} AP</Body></HUDCard><PanelSection title="Resource Storage / Upgrade Progress">{req ? types.map(t => <HUDCard key={t}><ResourceBar label={t} value={camp.progress[t]} max={req[t]} accent={t === 'energy' ? colors.blue : t === 'materials' ? colors.amber : colors.cyan}/><Body>{Math.round(campProgressPercent(camp, t) * 100)}% SYNCHRONIZED</Body></HUDCard>) : <HUDCard><Body>FORTRESS CAPACITY ONLINE. REGIONAL COMMAND FUNCTIONS STANDBY.</Body></HUDCard>}</PanelSection><PanelSection title="Contribution Panel"><HUDCard>{types.map(t => <View key={t} style={{ gap: space.xs }}><Body>{t.toUpperCase()} // OWNED {inv[t]}</Body><TextInput value={amounts[t] ? String(amounts[t]) : ''} keyboardType="number-pad" placeholder="000" placeholderTextColor={colors.muted} onChangeText={v => setAmounts(a => ({ ...a, [t]: Math.min(inv[t], Math.max(0, Number.parseInt(v || '0',10) || 0)) }))} style={{ borderWidth: 1, borderColor: colors.line, color: colors.text, padding: space.sm, letterSpacing: 2, minHeight:44 }}/></View>)}<Button disabled={!valid} onPress={() => { const ok=contribute(amounts); setFeedback(ok ? `Uploaded ${total} resources. ${total} AP awarded.` : 'Upload rejected: invalid contribution.'); if(ok) setAmounts({ data: 0, energy: 0, materials: 0 }); }}>Upload to Base</Button>{!valid && <Body>ENTER AT LEAST ONE RESOURCE WITHIN AVAILABLE STORAGE.</Body>}</HUDCard></PanelSection><ActionFeedback message={feedback}/></Screen>; }
