import { useState } from 'react';
import { View } from 'react-native';
import { ActionFeedback, Body, Button, EmptyState, HUDCard, PanelSection, ResourceBar, Screen, ScreenHeader } from '../components/ui';
import { CRAFTING_RECIPES, RESOURCE_EMOJI } from '../constants/balance';
import { useGameStore } from '../store/gameStore';
import { EquipmentItem, ResourceType } from '../types/game';
import { colors, space } from '../theme/theme';
const names: Record<EquipmentItem, string> = { scanner: 'Scanner Array', relayKey: 'Relay Key', fieldKit: 'Field Kit' };
const desc: Record<EquipmentItem, string> = { scanner: 'Extends local sweep resolution for resource discovery.', relayKey: 'Authorizes routing through captured field relays.', fieldKit: 'Deployable tactical kit for base and node operations.' };
export function InventoryScreen() { const inv = useGameStore(s => s.inventory); const eq = useGameStore(s => s.equipment); const craft = useGameStore(s => s.craft); const [feedback,setFeedback]=useState(''); const empty=inv.data+inv.energy+inv.materials+eq.scanner+eq.relayKey+eq.fieldKit===0; return <Screen><ScreenHeader title="Inventory Matrix" kicker="Resource command"/>{empty && <EmptyState title="Vault Empty" body="Scan the map to locate resources, then fabricate tactical assets."/>}<PanelSection title="Resources">{(['data', 'energy', 'materials'] as ResourceType[]).map(t => <HUDCard key={t}><ResourceBar label={t} value={inv[t]} max={Math.max(50, inv[t], 1)} accent={t === 'energy' ? colors.blue : t === 'materials' ? colors.amber : colors.cyan}/></HUDCard>)}</PanelSection><PanelSection title="Crafting / Fabrication">{(Object.keys(CRAFTING_RECIPES) as EquipmentItem[]).map(item => { const r = CRAFTING_RECIPES[item]; const missing = Object.entries(r).filter(([k, v]) => inv[k as ResourceType] < Number(v)).map(([k,v])=>`${Number(v)-inv[k as ResourceType]} ${k}`); const ok = missing.length===0; return <HUDCard key={item}><View style={{ flexDirection: 'row', gap: space.md, alignItems: 'center' }}><Body>{RESOURCE_EMOJI[item]}</Body><View style={{ flex: 1 }}><Body>{names[item]} // OWNED {eq[item]}</Body><Body>{desc[item]}</Body><Body>COST {Object.entries(r).map(([k, v]) => `${v} ${k}`).join(' + ')}</Body>{!ok && <Body>LOCKED // NEED {missing.join(' + ')}</Body>}</View></View><Button disabled={!ok} onPress={() => { const done=craft(item); setFeedback(done ? `${names[item]} fabricated` : `Insufficient resources for ${names[item]}`); }}>Build / Use {names[item]}</Button></HUDCard>; })}</PanelSection><PanelSection title="Tactical Assets">{(['scanner','relayKey','fieldKit'] as EquipmentItem[]).map(i=><HUDCard key={i}><Body>{RESOURCE_EMOJI[i]} {names[i]} // QTY {eq[i]}</Body><Body>{eq[i] > 0 ? 'READY IN FIELD LOADOUT' : 'NOT YET FABRICATED'}</Body></HUDCard>)}</PanelSection><ActionFeedback message={feedback}/></Screen>; }
