import { View } from 'react-native';
import { Body, Button, HUDCard, PanelSection, ResourceBar, Screen, ScreenHeader } from '../components/ui';
import { CRAFTING_RECIPES, RESOURCE_EMOJI } from '../constants/balance';
import { useGameStore } from '../store/gameStore';
import { EquipmentItem, ResourceType } from '../types/game';
import { colors, space } from '../theme/theme';
const names: Record<EquipmentItem, string> = { scanner: 'Scanner', relayKey: 'Relay Key', fieldKit: 'Field Kit' };
const desc: Record<EquipmentItem, string> = { scanner: 'Extends local sweep resolution for resource discovery.', relayKey: 'Authorizes remote routing through captured field relays.', fieldKit: 'Deployable tactical kit for base and node operations.' };
export function InventoryScreen() { const inv = useGameStore(s => s.inventory); const eq = useGameStore(s => s.equipment); const craft = useGameStore(s => s.craft); return <Screen><ScreenHeader title="Inventory Matrix" kicker="Resource command"/><PanelSection title="Inventory Resources">{(['data', 'energy', 'materials'] as ResourceType[]).map(t => <HUDCard key={t}><ResourceBar label={t} value={inv[t]} max={Math.max(100, inv[t])} accent={t === 'energy' ? colors.blue : t === 'materials' ? colors.amber : colors.cyan}/></HUDCard>)}</PanelSection><PanelSection title="Field Fabrication">{(Object.keys(CRAFTING_RECIPES) as EquipmentItem[]).map(item => { const r = CRAFTING_RECIPES[item]; const ok = Object.entries(r).every(([k, v]) => inv[k as ResourceType] >= Number(v)); return <HUDCard key={item}><View style={{ flexDirection: 'row', gap: space.md, alignItems: 'center' }}><Body>{RESOURCE_EMOJI[item]}</Body><View style={{ flex: 1 }}><Body>{names[item]} // OWNED {eq[item]}</Body><Body>{desc[item]}</Body><Body>COST {Object.entries(r).map(([k, v]) => `${v} ${k}`).join(' + ')}</Body></View></View><Button disabled={!ok} onPress={() => craft(item)}>Build {names[item]}</Button></HUDCard>; })}</PanelSection></Screen>; }
