import { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Text, View } from 'react-native';
import MapView, { Circle, Marker, UrlTile } from 'react-native-maps';
import { Button, Card, Screen, Title } from '../components/ui';
import { COLLECTION_RADIUS_METERS, PLAYER_INTERACTION_RADIUS_METERS, RESOURCE_EMOJI, RESOURCE_SPAWN_RADIUS_METERS } from '../constants/balance';
import { requestCurrentLocation } from '../services/locationService';
import { generateMockPlayers } from '../services/mockPlayerService';
import { spawnResources } from '../services/resourceService';
import { useGameStore } from '../store/gameStore';
import { Coordinates } from '../types/game';
import { haversineDistanceMeters } from '../utils/geo';
export function MapScreen(){ const [loc,setLoc]=useState<Coordinates>(); const [error,setError]=useState(''); const [modal,setModal]=useState(''); const resources=useGameStore(s=>s.resources); const setResources=useGameStore(s=>s.setResources); const collect=useGameStore(s=>s.collectResource); const greet=useGameStore(s=>s.greet); const greeted=useGameStore(s=>s.greetedPlayerIds); const players=useMemo(()=>loc?generateMockPlayers(loc):[],[loc]); useEffect(()=>{requestCurrentLocation().then(c=>{setLoc(c); if(resources.length===0)setResources(spawnResources(c));}).catch(e=>setError(e.message));},[]); if(error)return <Screen><Title>Map unavailable</Title><Card><Text>{error}</Text></Card></Screen>; if(!loc)return <Screen><Title>Finding your territory…</Title></Screen>; const active=resources.filter(r=>!r.collected); return <Screen><Title>Tribal Map</Title><View style={{height:330,borderRadius:18,overflow:'hidden'}}><MapView style={{flex:1}} initialRegion={{...loc,latitudeDelta:0.01,longitudeDelta:0.01}} showsUserLocation><UrlTile urlTemplate="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" maximumZ={19} flipY={false}/><Circle center={loc} radius={COLLECTION_RADIUS_METERS} strokeColor="rgba(83,107,54,.8)" fillColor="rgba(83,107,54,.18)"/><Circle center={loc} radius={PLAYER_INTERACTION_RADIUS_METERS} strokeColor="rgba(255,255,255,.8)" fillColor="rgba(255,255,255,.08)"/>{active.map(r=><Marker key={r.id} coordinate={r.coordinates} title={r.type} description={`${haversineDistanceMeters(loc,r.coordinates)}m away`}>{<Text style={{fontSize:24}}>{RESOURCE_EMOJI[r.type]}</Text>}</Marker>)}{players.map(p=><Marker key={p.id} coordinate={p.coordinates} title={p.username} description={`${p.distance}m • ${p.status}`}>{<Text style={{fontSize:24}}>🧍</Text>}</Marker>)}</MapView></View><Button onPress={()=>setResources(spawnResources(loc,18,RESOURCE_SPAWN_RADIUS_METERS))}>Regenerate resources (testing)</Button><Card><Text style={{fontWeight:'800'}}>Nearby resources</Text>{active.length===0?<Text>No resources nearby. Regenerate to test.</Text>:active.slice(0,6).map(r=>{const d=haversineDistanceMeters(loc,r.coordinates); return <Button key={r.id} disabled={d>COLLECTION_RADIUS_METERS} onPress={()=>collect(r.id)}>{RESOURCE_EMOJI[r.type]} {r.type} • {d}m {d>COLLECTION_RADIUS_METERS?'(too far)':'Collect'}</Button>})}</Card><Card><Text style={{fontWeight:'800'}}>Nearby players</Text>{players.map(p=><View key={p.id}><Text>{p.username} • {p.tribe} • L{p.level} • {p.distance}m</Text>{p.distance<=PLAYER_INTERACTION_RADIUS_METERS&&<View><Button disabled={greeted.includes(p.id)} onPress={()=>greet(p.id)}>Greet (+5 XP)</Button><Button onPress={()=>setModal('Trading foundation placeholder')}>Trade request</Button><Button onPress={()=>setModal('Combat will come later')}>Challenge</Button></View>}</View>)}</Card><Modal visible={!!modal} transparent><Screen><Card><Text>{modal}</Text><Button onPress={()=>setModal('')}>Close</Button></Card></Screen></Modal></Screen> }
