import { useMemo, useState } from 'react';
import { View } from 'react-native';
import { Button, EmptyState, MissionCard, Screen, ScreenHeader, ActionFeedback } from '../components/ui';
import { useGameStore } from '../store/gameStore';
import { Mission, MissionFilter } from '../types/game';
import { space } from '../theme/theme';

const filters: MissionFilter[] = ['nearby', 'clan', 'daily', 'special'];
export function MissionsScreen(){ const stats=useGameStore(s=>s.stats); const inv=useGameStore(s=>s.inventory); const claim=useGameStore(s=>s.claimMission); const [filter,setFilter]=useState<MissionFilter>('nearby'); const [claimed,setClaimed]=useState<Record<string, boolean>>({}); const [feedback,setFeedback]=useState(''); const total=inv.data+inv.energy+inv.materials; const missions=useMemo<Mission[]>(()=>[
 {id:'m-data',filter:'nearby',title:'DATA INTERCEPT',objective:'Collect 20 DATA',difficulty:'easy',distanceMeters:350,reward:'75 AP + Collector badge',progress:Math.min(inv.data,20),target:20,status:claimed['m-data']?'claimed':inv.data>=20?'completed':'active'},
 {id:'m-patrol',filter:'nearby',title:'LONG RANGE PATROL',objective:'Travel 2 km through contested grid sectors',difficulty:'medium',distanceMeters:2000,reward:'100 AP + Explorer badge',progress:Math.min(Math.round(stats.distanceMeters),2000),target:2000,status:claimed['m-patrol']?'claimed':stats.distanceMeters>=2000?'completed':'available'},
 {id:'m-scout',filter:'clan',title:'ZONE TRIANGULATION',objective:'Signal 3 nearby agents',difficulty:'medium',distanceMeters:600,reward:'60 AP + Scout badge',progress:Math.min(stats.playersGreeted,3),target:3,status:claimed['m-scout']?'claimed':stats.playersGreeted>=3?'completed':'active'},
 {id:'m-base',filter:'clan',title:'INFRASTRUCTURE PUSH',objective:'Contribute resources to a Base',difficulty:'easy',distanceMeters:100,reward:'Materials cache + 75 AP',progress:Math.min(stats.resourcesContributed,1),target:1,status:claimed['m-base']?'claimed':stats.resourcesContributed>=1?'completed':'available'},
 {id:'m-sweep',filter:'daily',title:'RESOURCE SWEEP',objective:'Secure 30 total resources',difficulty:'hard',distanceMeters:900,reward:'90 AP',progress:Math.min(total+stats.resourcesCollected,30),target:30,status:claimed['m-sweep']?'claimed':total+stats.resourcesCollected>=30?'completed':'active'},
 {id:'m-elite',filter:'special',title:'BLACKSITE BREACH',objective:'Reach clearance level 4 to unlock elite operations',difficulty:'elite',distanceMeters:4200,reward:'250 AP + Rare badge',progress:stats.level,target:4,status:stats.level>=4?'available':'locked'}], [inv.data,total,stats,claimed]); const visible=missions.filter(m=>m.filter===filter); return <Screen><ScreenHeader title="Mission Uplink" kicker="Operational contracts"/><View style={{flexDirection:'row',flexWrap:'wrap',gap:space.sm}}>{filters.map(f=><Button key={f} compact onPress={()=>setFilter(f)}>{filter===f?'◆ ':''}{f}</Button>)}</View>{visible.length ? visible.map(m=><MissionCard key={m.id} mission={m} onPress={()=>{ if(m.status==='completed'){ claim(75); setClaimed(c=>({...c,[m.id]:true})); setFeedback(`${m.title} reward claimed`); } else setFeedback(`${m.title} set as active objective`); }}/>) : <EmptyState title="No Signals" body="No missions match this channel. Switch filters or scan the map for contracts."/>}<ActionFeedback message={feedback}/></Screen> }
