import { CampLevel, EquipmentItem, Inventory, ResourceType } from '../types/game';
export const AP_REWARDS = { collectResource: 10, craftItem: 20, greetPlayer: 5, contributePerUnit: 1, mission: 75 } as const;
export const XP_REWARDS = AP_REWARDS;
export const LEVEL_THRESHOLDS = [0, 100, 300, 700, 1500, 3000] as const;
export const RESOURCE_SPAWN_RADIUS_METERS = 500;
export const COLLECTION_RADIUS_METERS = 50;
export const PLAYER_INTERACTION_RADIUS_METERS = 50;
export const BASE_INTERACTION_RADIUS_METERS = 100;
export const RESOURCE_TYPES: ResourceType[] = ['data','energy','materials'];
export const CRAFTING_RECIPES: Record<EquipmentItem, Partial<Inventory>> = { scanner:{data:8,energy:4}, relayKey:{data:5,materials:6}, fieldKit:{energy:5,materials:5} };
export const CAMP_LEVEL_REQUIREMENTS: Record<CampLevel, Inventory | null> = { 0:{data:100,energy:100,materials:75}, 1:{data:250,energy:250,materials:150}, 2:{data:500,energy:500,materials:300}, 3:{data:900,energy:900,materials:600}, 4:null };
export const BASE_LEVEL_NAMES = ['BEACON','RELAY','HUB','COMMAND CENTER','FORTRESS'] as const;
export const RESOURCE_EMOJI: Record<ResourceType|EquipmentItem,string> = { data:'◇', energy:'⬡', materials:'▣', scanner:'⌖', relayKey:'⎔', fieldKit:'✚' };
