import { PropsWithChildren, ReactNode, useEffect, useRef } from 'react';
import { Animated, Pressable, ScrollView, StyleSheet, Text, View, ViewStyle, useWindowDimensions } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, layout, space, tribeMeta } from '../theme/theme';
import { Faction } from '../types/game';

export function Screen({ children, scroll = true }: PropsWithChildren<{ scroll?: boolean }>) {
  const insets = useSafeAreaInsets();
  const { width } = useWindowDimensions();
  const content = <View style={[styles.container, { maxWidth: layout.maxWidth, width: Math.min(width, layout.maxWidth) }]}>{children}</View>;
  return <SafeAreaView style={styles.screen} edges={['top', 'left', 'right']}>
    {scroll ? <ScrollView contentContainerStyle={[styles.scroll, { paddingBottom: layout.tabBarHeight + insets.bottom + space.lg }]} showsVerticalScrollIndicator={false}>{content}</ScrollView> : content}
  </SafeAreaView>;
}

export const ScreenContainer = ({ children }: PropsWithChildren) => <View style={styles.container}>{children}</View>;

export function HUDCard({ children, style }: PropsWithChildren<{ style?: ViewStyle | ViewStyle[] }>) { return <View style={[styles.card, style]}><View style={styles.cornerTop}/><View style={styles.cornerBottom}/>{children}</View>; }
export const Card = HUDCard;
export function PanelSection({ title, children }: PropsWithChildren<{ title: string }>) { return <View style={styles.section}><Label>{title}</Label>{children}</View>; }
export function ScreenHeader({ title, kicker, right }: { title: string; kicker?: string; right?: ReactNode }) { return <View style={styles.header}><View style={{ flex: 1 }}><Label>{kicker ?? 'COMMAND INTERFACE'}</Label><Title>{title}</Title></View>{right}</View>; }
export function Title({ children }: PropsWithChildren) { return <Text style={styles.title}>{children}</Text>; }
export function Label({ children }: PropsWithChildren) { return <Text style={styles.label}>{children}</Text>; }
export function Body({ children }: PropsWithChildren) { return <Text style={styles.body}>{children}</Text>; }

export function HUDButton({ children, onPress, disabled, accent = colors.cyan, compact = false }: { children: ReactNode; onPress?: () => void; disabled?: boolean; accent?: string; compact?: boolean }) {
  return <Pressable onPress={onPress} disabled={disabled} style={({ pressed }) => [styles.button, compact && styles.buttonCompact, { borderColor: disabled ? colors.disabled : accent }, pressed && !disabled && { backgroundColor: `${accent}22`, transform: [{ scale: 0.98 }] }, disabled && styles.disabled]}><Text style={[styles.buttonText, { color: disabled ? colors.muted : accent }]} numberOfLines={2}>{children}</Text></Pressable>;
}
export const HexButton = HUDButton; export const Button = HUDButton;

export function ResourceBar({ label, value, max = 100, accent = colors.cyan }: { label: string; value: number; max?: number; accent?: string }) { const pct = max > 0 ? value / max : 0; return <View style={styles.resource}><View style={styles.row}><Label>{label}</Label><Text style={styles.value}>{value}/{max}</Text></View><ProgressBar value={pct} accent={accent}/></View>; }
export function ProgressBar({ value, accent = colors.cyan }: { value: number; accent?: string }) { return <View style={styles.track}><View style={[styles.fill, { width: `${Math.max(0, Math.min(100, Math.round(value * 100)))}%`, backgroundColor: accent, shadowColor: accent }]}/></View>; }
export function FactionBar({ left, right }: { left: number; right: number }) { const total = Math.max(1, left + right); return <View style={styles.factionBar}><View style={[styles.factionFill, { flex: left / total, backgroundColor: colors.green }]}/><View style={[styles.factionFill, { flex: right / total, backgroundColor: colors.cyan }]}/></View>; }
export function StatCard({ label, value }: { label: string; value: ReactNode }) { return <HUDCard style={styles.stat}><Text style={styles.value}>{value}</Text><Label>{label}</Label></HUDCard>; }
export function AchievementBadge({ name, description, unlocked }: { name: string; description: string; unlocked: boolean }) { return <View style={[styles.achievement, { borderColor: unlocked ? colors.violet : colors.disabled }]}><Text style={[styles.achievementIcon, { color: unlocked ? colors.violet : colors.disabled }]}>{unlocked ? '⬢' : '⬡'}</Text><Label>{name}</Label><Body>{description}</Body></View>; }
export function FactionBadge({ faction }: { faction: Faction }) { const meta = tribeMeta[faction]; return <View style={[styles.badge, { borderColor: meta.accent }]}><Text style={[styles.badgeText, { color: meta.accent }]}>{meta.short}</Text></View>; }
export function TacticalModal({ children }: PropsWithChildren) { return <View style={styles.modal}><HUDCard style={{ borderColor: colors.amber }}>{children}</HUDCard></View>; }
export function MissionCard({ title, objective, reward, progress, target, completed }: { title: string; objective: string; reward: string; progress: number; target: number; completed: boolean }) { return <HUDCard style={{ borderColor: completed ? colors.green : colors.line }}><Label>{completed ? 'MISSION COMPLETE' : 'ACTIVE DIRECTIVE'}</Label><Text style={styles.agent}>{title}</Text><Body>{objective}</Body><ProgressBar value={progress / target} accent={completed ? colors.green : colors.amber}/><Body>{progress}/{target} • REWARD {reward}</Body></HUDCard>; }
export function ScanSweep() { const y = useRef(new Animated.Value(0)).current; useEffect(() => { Animated.loop(Animated.sequence([Animated.timing(y, { toValue: 1, duration: 2200, useNativeDriver: true }), Animated.timing(y, { toValue: 0, duration: 0, useNativeDriver: true })])).start(); }, [y]); return <Animated.View pointerEvents="none" style={[styles.sweep, { transform: [{ translateY: y.interpolate({ inputRange: [0, 1], outputRange: [0, 420] }) }] }]}/>; }

const font = 'System';
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.void }, scroll: { alignItems: 'center', padding: space.md }, container: { alignSelf: 'center', gap: space.md }, card: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line, padding: space.md, gap: space.sm, overflow: 'hidden' }, cornerTop: { position: 'absolute', right: -1, top: -1, width: 22, height: 22, borderTopWidth: 2, borderRightWidth: 2, borderColor: colors.cyan }, cornerBottom: { position: 'absolute', left: -1, bottom: -1, width: 22, height: 22, borderBottomWidth: 2, borderLeftWidth: 2, borderColor: colors.blue }, section: { gap: space.sm }, header: { flexDirection: 'row', alignItems: 'center', gap: space.md }, title: { fontFamily: font, fontSize: 24, fontWeight: '300', letterSpacing: 3, color: colors.text, textTransform: 'uppercase' }, label: { fontFamily: font, fontSize: 11, fontWeight: '800', letterSpacing: 2, color: colors.muted, textTransform: 'uppercase' }, body: { fontFamily: font, fontSize: 13, lineHeight: 18, letterSpacing: 1, color: colors.text, textTransform: 'uppercase' }, agent: { fontSize: 18, fontWeight: '800', letterSpacing: 2, color: colors.text, textTransform: 'uppercase' }, button: { minHeight: 48, borderWidth: 1, paddingVertical: space.sm, paddingHorizontal: space.md, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,229,255,.06)' }, buttonCompact: { minHeight: 40, paddingHorizontal: space.sm }, disabled: { backgroundColor: 'rgba(38,51,61,.5)' }, buttonText: { fontWeight: '900', fontSize: 12, letterSpacing: 1.5, textTransform: 'uppercase', textAlign: 'center' }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: space.sm }, resource: { gap: space.xs }, value: { color: colors.text, fontSize: 18, fontWeight: '900', letterSpacing: 2 }, track: { height: 10, backgroundColor: '#071019', borderWidth: 1, borderColor: colors.line, overflow: 'hidden' }, fill: { height: 8, shadowOpacity: .9, shadowRadius: 8 }, factionBar: { height: 14, flexDirection: 'row', borderWidth: 1, borderColor: colors.line, backgroundColor: colors.black }, factionFill: { height: '100%' }, stat: { width: '48%', minHeight: 86 }, achievement: { width: '23%', minWidth: 72, borderWidth: 1, padding: space.xs, alignItems: 'center', gap: space.xs }, achievementIcon: { fontSize: 24 }, badge: { borderWidth: 1, paddingHorizontal: space.sm, paddingVertical: space.xs, backgroundColor: 'rgba(255,255,255,.03)' }, badgeText: { fontSize: 10, fontWeight: '900', letterSpacing: 1.4 }, modal: { flex: 1, backgroundColor: 'rgba(5,7,10,.82)', justifyContent: 'center', padding: space.lg }, sweep: { position: 'absolute', left: 0, right: 0, height: 2, backgroundColor: colors.cyan, shadowColor: colors.cyan, shadowOpacity: 1, shadowRadius: 12 } });
