import { PropsWithChildren, ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { colors, tribeMeta } from '../theme/theme';
import { Faction } from '../types/game';
export function Screen({children}:PropsWithChildren){return <View style={styles.screen}><View style={styles.grid}>{children}</View></View>}
export function HUDPanel({children,style}:PropsWithChildren<{style?:ViewStyle}>){return <View style={[styles.panel,style]}><View style={styles.corner}/>{children}</View>}
export const Card = HUDPanel;
export function Title({children}:PropsWithChildren){return <Text style={styles.title}>{children}</Text>}
export function Label({children}:PropsWithChildren){return <Text style={styles.label}>{children}</Text>}
export function Body({children}:PropsWithChildren){return <Text style={styles.body}>{children}</Text>}
export function HexButton({children,onPress,disabled,accent=colors.cyan}:{children:ReactNode;onPress?:()=>void;disabled?:boolean;accent?:string}){return <Pressable onPress={onPress} disabled={disabled} style={[styles.hexButton,{borderColor:disabled?colors.disabled:accent},disabled&&styles.disabled]}><Text style={[styles.buttonText,{color:disabled?colors.muted:accent}]}>{children}</Text></Pressable>}
export const Button = HexButton;
export function ProgressBar({value,accent=colors.cyan}:{value:number;accent?:string}){return <View style={styles.track}><View style={[styles.fill,{width:`${Math.min(100,Math.round(value*100))}%`,backgroundColor:accent,shadowColor:accent}]}/></View>}
export function FactionBadge({faction}:{faction:Faction}){const meta=tribeMeta[faction]; return <View style={[styles.badge,{borderColor:meta.accent}]}><Text style={[styles.badgeText,{color:meta.accent}]}>{meta.label}</Text></View>}
export function AgentCard({name,faction,meta}:{name:string;faction:Faction;meta:string}){return <HUDPanel><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={styles.agent}>{name}</Text><FactionBadge faction={faction}/></View><Body>{meta}</Body></HUDPanel>}
export function TacticalModal({children}:PropsWithChildren){return <View style={styles.modal}><HUDPanel style={{borderColor:colors.amber}}>{children}</HUDPanel></View>}
export function MissionCard({title,objective,reward,progress,target,completed}:{title:string;objective:string;reward:string;progress:number;target:number;completed:boolean}){return <HUDPanel style={{borderColor:completed?colors.green:colors.line}}><Label>{completed?'MISSION COMPLETE':'ACTIVE DIRECTIVE'}</Label><Text style={styles.agent}>{title}</Text><Body>{objective}</Body><ProgressBar value={progress/target} accent={completed?colors.green:colors.amber}/><Body>{progress}/{target} • REWARD {reward}</Body></HUDPanel>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.void},grid:{flex:1,padding:14,gap:12,backgroundColor:colors.void},panel:{backgroundColor:'rgba(10,15,20,.92)',borderWidth:1,borderColor:colors.line,padding:14,gap:8},corner:{position:'absolute',right:-1,top:-1,width:22,height:22,borderTopWidth:2,borderRightWidth:2,borderColor:colors.cyan},title:{fontSize:26,fontWeight:'200',letterSpacing:3,color:colors.text,marginVertical:4,textTransform:'uppercase'},label:{fontSize:11,fontWeight:'800',letterSpacing:2,color:colors.muted,textTransform:'uppercase'},body:{fontSize:13,letterSpacing:1,color:colors.text,textTransform:'uppercase'},agent:{fontSize:18,fontWeight:'700',letterSpacing:2,color:colors.text,textTransform:'uppercase'},hexButton:{borderWidth:1,paddingVertical:12,paddingHorizontal:14,alignItems:'center',marginVertical:3,backgroundColor:'rgba(0,229,255,.06)'},disabled:{backgroundColor:'rgba(38,51,61,.5)'},buttonText:{fontWeight:'800',fontSize:13,letterSpacing:2,textTransform:'uppercase'},track:{height:10,backgroundColor:'#071019',borderWidth:1,borderColor:colors.line,overflow:'hidden'},fill:{height:8,shadowOpacity:.9,shadowRadius:8},badge:{borderWidth:1,paddingHorizontal:8,paddingVertical:4,backgroundColor:'rgba(255,255,255,.03)'},badgeText:{fontSize:10,fontWeight:'800',letterSpacing:1.4},modal:{flex:1,backgroundColor:'rgba(5,7,11,.82)',justifyContent:'center',padding:24}});
